POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Multithreading Javascript",
    "author": "Max Peng",
    "url": "https://medium.com/techtrument/multithreading-javascript-46156179cf9a",
    "likes": 1800
  }